# Generated by Django 5.1.6 on 2025-02-18 03:34

import auth_server_mfa.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server_mfa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mfatoken',
            name='auth_server_user_id_2204b7_idx',
        ),
        migrations.RemoveField(
            model_name='mfatoken',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='mfatoken',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='mfatoken',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mfatoken',
            name='last_used_at',
        ),
        migrations.RemoveField(
            model_name='mfatoken',
            name='secret',
        ),
        migrations.AddField(
            model_name='mfatoken',
            name='expires_at',
            field=models.DateTimeField(default=auth_server_mfa.models.get_expiry_time),
        ),
        migrations.AddField(
            model_name='mfatoken',
            name='token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='mfatoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mfatoken',
            index=models.Index(fields=['user', 'token'], name='auth_server_user_id_fe224f_idx'),
        ),
        migrations.AddIndex(
            model_name='mfatoken',
            index=models.Index(fields=['expires_at'], name='auth_server_expires_30922a_idx'),
        ),
    ]
